// Premraj Gill
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class Main {

    public static void main(String[] args) {
        System.out.println(evenFibonacci(4000000));
    }

    public static int evenFibonacci(int x){
        int finalSum = 0;
        int n1 = 1;
        int n2 = 2;
        int n = 0;
// As per the problems specifications I always start at 1 and 2
        while(finalSum <= x){
            n = n1 +n2;
            n1 = n2;
            n2 =n;

            if(n%2 ==0){
                finalSum = finalSum +n;
            }

        } return finalSum;





    }





}

